# Do not change
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
maven_group=dev.ftb.mods

# Feel free to update
archives_base_name=ftb-evolution-companion

mod_name=FTB Evolution 2 Companion
mod_id=ftbevolutioncompanion
mod_version=2-snapshot.104

mod_url=https://curseforge.com/minecraft/mc-mods/ftb-evolution-companion
mod_description=Companion mod for the FTB Evolution 2 modpack

minecraft_version=26.1.2
neoforge_full_version=26.1.2.109
neoforge_loader_version=11
neo_version_range=[26.1.2,)

#CurseForge
curseforge_id=-1

#Deps
ftb_library_version=26.1.2.8
ftb_quests_version=26.1.2.8
ftb_teams_version=26.1.2.4
ftb_chunks_version=26.1.2.8
jei_version=29.22.0.73
cloth_config_version=26.1.154
geckolib_version=5.5.2
geckolib_modrinth_id=xfVfPcoC
iris_modrinth_id=qE5Y7GrZ
hats_curse_file_id=8035007
enderio_curse_file_id=8832914
curios_curse_file_id=8463519
ars_magica_legacy_curse_file_id=8715112
neovitae_curse_file_id=8970064
animusnv_curse_file_id=8858844
evilcraft_curse_file_id=8858711
cyclopscore_curse_file_id=8859200
occultism_curse_file_id=8903702
apothic_enchanting_curse_file_id=8171092
placebo_curse_file_id=8502256
roots_classic_curse_file_id=8757288
witchery_curse_file_id=8905674
witchery_forbidden_magic_curse_file_id=8905687
kotlinforforge_curse_file_id=8335648
anima_curse_file_id=8966144
irons_artifice_curse_file_id=8974275
