# Do not change
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
maven_group=dev.ftb.mods

# Feel free to update
archives_base_name=ftb-evolution-companion

mod_name=FTB Evolution 2 Companion
mod_id=ftbevolutioncompanion
mod_version=2-snapshot.9

mod_url=https://curseforge.com/minecraft/mc-mods/ftb-evolution-companion
mod_description=Companion mod for the FTB Evolution 2 modpack

minecraft_version=26.1.2
neoforge_full_version=26.1.2.95
neoforge_loader_version=11
neo_version_range=[26.1.2,)

#CurseForge
curseforge_id=-1

#Deps
ftb_library_version=26.1.2.6
jei_version=29.22.0.73
