# Do not change
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
maven_group=dev.ftb.mods

# Feel free to update
parchment_minecraft_version=${mc_version}
parchment_mappings_version=2024.11.17

archives_base_name=ftb-evolution-companion

mod_name=FTB Evolution Companion
mod_id=ftbevolutioncompanion
mod_version=1

mod_url=https://curseforge.com/minecraft/mc-mods/ftb-evolution-companion
mod_description=Companion mod for FTB Evolution

minecraft_version=1.21.1
# https://minecraft.fandom.com/wiki/Pack_format
pack_format=15

loader_version_range=[4,)
mod_loader_range=[${mc_base},)
neo_version=203

#CurseForge
curseforge_id=1647403

#Deps
ftb_library_version=2101.1.35
ftb_essentials_version=2101.1.10
architectury_version=13.0.8
create_version=6.0.10-281
ponder_version=1.0.82+mc1.21.1
sable_companion_version=1.6.0

#Deps - CurseForge file ids
sable_file=8242682
ae2_file=7027323
jade_file=7545219
cyclops_core_file=8006281
integrated_dynamics_file=8039124
ars_nouveau_file=8262663
enderio_version=v8.2.10-beta
